/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.Constantes;
import ec.edu.ups.controlador.GestionarContacto;
import ec.edu.ups.modelo.Contacto;
import java.util.LinkedList;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Core i5 11va
 */
public class AgendaContactos extends javax.swing.JFrame {

    private ContactosTbl dataTbl;
    private GestionarContacto app;
    
    private ResourceBundle rb;
    
    /**
     * Creates new form AgendaContactos
     */
    public AgendaContactos() {
        initComponents();
        
        this.rb = ResourceBundle.getBundle( Constantes.RECURSO, Locale.ENGLISH );
        this.cargarIdioma();
        
        this.setLocationRelativeTo(null);
        
        this.app = new GestionarContacto();
        
        this.dataTbl = new ContactosTbl();
        this.dataTbl.verTabla( this.contactosTbl, this.rb );
        
        this.cargarTabla();
    }
    
    public void cargarIdioma() {
        this.setTitle( this.rb.getString( Constantes.VENTANA_TITULO ) );
        this.tituloLbl.setText( this.rb.getString( Constantes.VENTANA_TITULO ) );            
        this.buscarLbl.setText( this.rb.getString( Constantes.VENTANA_BUSCAR ) + ":" );
        this.buscarBtn.setText( this.rb.getString( Constantes.VENTANA_BUSCAR ) );
        this.agregarBtn.setText( this.rb.getString( Constantes.VENTANA_AGREGAR ) );
        this.cerrarBtn.setText( this.rb.getString( Constantes.VENTANA_CERRAR ) );
    }
    
    public void cargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) this.contactosTbl.getModel();
        LinkedList<Contacto> contactos = this.app.getContactos();
        for (Contacto contacto : contactos) {
            modelo.addRow( contacto.getDatos(this.rb) );
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLbl = new javax.swing.JLabel();
        buscarLbl = new javax.swing.JLabel();
        buscarBtn = new javax.swing.JButton();
        buscarTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        contactosTbl = new javax.swing.JTable();
        agregarBtn = new javax.swing.JButton();
        cerrarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloLbl.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        tituloLbl.setText("Agenda de Contactos");

        buscarLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buscarLbl.setText("Buscar:");

        buscarBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buscarBtn.setText("Buscar");
        buscarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtnActionPerformed(evt);
            }
        });

        buscarTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        contactosTbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        contactosTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        contactosTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactosTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(contactosTbl);

        agregarBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        agregarBtn.setText("Agregar");
        agregarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtnActionPerformed(evt);
            }
        });

        cerrarBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cerrarBtn.setText("Cerrar");
        cerrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 172, Short.MAX_VALUE)
                                        .addComponent(tituloLbl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buscarLbl)
                                        .addGap(18, 18, 18)
                                        .addComponent(buscarTxt)))
                                .addGap(18, 18, 18)
                                .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(agregarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cerrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tituloLbl)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarLbl)
                    .addComponent(buscarBtn)
                    .addComponent(buscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(agregarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(cerrarBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtnActionPerformed
        VContacto contacto = new VContacto((DefaultTableModel) this.contactosTbl.getModel(), this.app, this.rb);
        contacto.setVisible( true );
    }//GEN-LAST:event_agregarBtnActionPerformed

    private void cerrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarBtnActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cerrarBtnActionPerformed

    private void buscarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtnActionPerformed
        String texto = this.buscarTxt.getText();
        
        DefaultTableModel modelo = (DefaultTableModel) this.contactosTbl.getModel();
        modelo.setRowCount(0);
        
        for (int i=0; i < this.app.getContactos().size(); i++) {
            Contacto contacto = this.app.getContactos().get(i);
            if (contacto.getNombre().contains(texto) || contacto.getApellido().contains(texto) || contacto.getTelefono().contains(texto)) {
                modelo.addRow( contacto.getDatos(this.rb) );
            }
        }
    }//GEN-LAST:event_buscarBtnActionPerformed

    private void contactosTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactosTblMouseClicked
        // se obtiene el indice de la columna (0 a tamanio de las columnas) en la tabla donde se le da click.
        int columna = this.contactosTbl.getColumnModel().getColumnIndexAtX( evt.getX() );
        // se obtiene el indice de la fila (0 a tamanio de las filas) en la tabla donde se le da click.
        int fila = evt.getY() / this.contactosTbl.getRowHeight();
        
        if (fila < this.contactosTbl.getRowCount() && fila >= 0 &&
                columna < this.contactosTbl.getColumnCount() && columna >= 0) {
            Object value = this.contactosTbl.getValueAt(fila, columna);
            if (value instanceof JButton) {
                ((JButton)value).doClick();
                JButton boton = (JButton) value;

                Contacto contacto = new Contacto();
                contacto.setNombre( this.contactosTbl.getValueAt( this.contactosTbl.getSelectedRow(), 0).toString() );
                contacto.setApellido( this.contactosTbl.getValueAt( this.contactosTbl.getSelectedRow(), 1).toString() );
                contacto.setTelefono( this.contactosTbl.getValueAt( this.contactosTbl.getSelectedRow(), 2).toString() );

                contacto = this.app.buscarIdPorNombreApellidoTelefono(contacto);
                
                if (boton.getName().equals("M")) {
                    
                    VContacto vcontacto = new VContacto((DefaultTableModel) this.contactosTbl.getModel(), this.app, contacto, this.contactosTbl.getSelectedRow(), this.rb);
                    vcontacto.setVisible( true );
                }
                if (boton.getName().equals("E")) {
                    Object[] options = {"Si", "No"};
                    int n = JOptionPane.showOptionDialog(this,
                                "Esta seguro de eliminar el registro?",
                                "Agenda de Contactos",
                                JOptionPane.YES_NO_OPTION,
                                JOptionPane.QUESTION_MESSAGE,
                                null,     //do not use a custom Icon
                                options,  //the titles of buttons
                                options[1]); //default button title
                    if (n == 0) {
                        DefaultTableModel modelo = (DefaultTableModel) this.contactosTbl.getModel();
                        modelo.removeRow( fila );
                        
                        this.app.eliminar( contacto );
                    }
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_contactosTblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaContactos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JButton buscarBtn;
    private javax.swing.JLabel buscarLbl;
    private javax.swing.JTextField buscarTxt;
    private javax.swing.JButton cerrarBtn;
    private javax.swing.JTable contactosTbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tituloLbl;
    // End of variables declaration//GEN-END:variables
}
