/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.Constantes;
import ec.edu.ups.controlador.GestionarContacto;
import ec.edu.ups.modelo.Contacto;
import java.util.LinkedList;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Core i5 11va
 */
public class VContacto extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    private GestionarContacto app;
    
    private Contacto contacto;
    private int filaSeleccionada;
    
    private ResourceBundle recurso;
    
    public VContacto(DefaultTableModel modelo, GestionarContacto app, Contacto contacto, int filaSeleccionada, ResourceBundle recurso) {
        initComponents();
        this.recurso = recurso;
        this.cargarIdioma();
        
        this.setLocationRelativeTo( null );
        this.setDefaultCloseOperation( HIDE_ON_CLOSE );
        
        this.modelo = modelo;
        this.app = app;
        this.contacto = contacto;
        this.filaSeleccionada = filaSeleccionada;
        
        this.nombreTxt.setText( this.contacto.getNombre() );
        this.apellidoTxt.setText( this.contacto.getApellido() );
        this.telefonoTxt.setText( this.contacto.getTelefono() );
        
        this.contacto = this.app.buscarIdPorNombreApellidoTelefono( this.contacto );
    }
    
    public VContacto(DefaultTableModel modelo, GestionarContacto app, ResourceBundle recurso) {
        initComponents();
        this.recurso = recurso;
        this.cargarIdioma();
        
        this.setLocationRelativeTo( null );
        this.setDefaultCloseOperation( HIDE_ON_CLOSE );
        
        this.modelo = modelo;
        this.app = app;
        this.contacto = null;
    }
    
    public void cargarIdioma() {
        this.tituloLbl.setText( this.recurso.getString( Constantes.CONTACTO_TITULO ) );
        this.nombreLbl.setText( this.recurso.getString( Constantes.CONTACTO_NOMBRE ) + ":" );
        this.apellidoLbl.setText( this.recurso.getString( Constantes.CONTACTO_APELLIDO ) + ":" );
        this.telefonoLbl.setText( this.recurso.getString( Constantes.CONTACTO_TELEFONO ) + ":" );
        this.cancelarBtn.setText( this.recurso.getString( Constantes.VENTANA_CANCELAR ) );
        this.guardarBtn.setText( this.recurso.getString( Constantes.VENTANA_GUARDAR ) );
    }
    
    public void cargarDatos() {
        this.modelo.setRowCount(0);
        
        LinkedList<Contacto> contactos = this.app.getContactos();
        for (Contacto contacto : contactos) {
            this.modelo.addRow( contacto.getDatos(this.recurso) );
        }        
    }
    
    /**
     * Creates new form VContacto
     */
    public VContacto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloLbl = new javax.swing.JLabel();
        nombreLbl = new javax.swing.JLabel();
        apellidoLbl = new javax.swing.JLabel();
        telefonoLbl = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        apellidoTxt = new javax.swing.JTextField();
        telefonoTxt = new javax.swing.JTextField();
        cancelarBtn = new javax.swing.JButton();
        guardarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tituloLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloLbl.setText("Gestion de Contacto");

        nombreLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombreLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombreLbl.setText("Nombre:");

        apellidoLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        apellidoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        apellidoLbl.setText("Apellido:");

        telefonoLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telefonoLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telefonoLbl.setText("Teléfono:");

        nombreTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        apellidoTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        telefonoTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        cancelarBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        guardarBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        guardarBtn.setText("Guardar");
        guardarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidoLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telefonoLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(telefonoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addComponent(apellidoTxt)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 209, Short.MAX_VALUE)
                        .addComponent(cancelarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(guardarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(nombreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nombreTxt)))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(tituloLbl)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLbl))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidoLbl))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoLbl))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarBtn)
                    .addComponent(guardarBtn))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void guardarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnActionPerformed
        if (this.contacto == null) {
            this.contacto = new Contacto();
            
            this.contacto.setNombre( this.nombreTxt.getText() );
            this.contacto.setApellido( this.apellidoTxt.getText() );
            this.contacto.setTelefono( this.telefonoTxt.getText() );

            this.app.registrar( this.contacto );
            this.cargarDatos();

            JOptionPane.showMessageDialog(this, "Contacto registrado.");            
        } else if (this.contacto != null) {            
            this.contacto.setNombre( this.nombreTxt.getText() );
            this.contacto.setApellido( this.apellidoTxt.getText() );
            this.contacto.setTelefono( this.telefonoTxt.getText() );

            this.app.modificar( this.contacto );
            
            this.modelo.setValueAt(this.contacto.getNombre(), this.filaSeleccionada, 0);
            this.modelo.setValueAt(this.contacto.getApellido(), this.filaSeleccionada, 1);
            this.modelo.setValueAt(this.contacto.getTelefono(), this.filaSeleccionada, 2);            
        }
        this.setVisible(false);
    }//GEN-LAST:event_guardarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VContacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoLbl;
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JButton guardarBtn;
    private javax.swing.JLabel nombreLbl;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JLabel telefonoLbl;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JLabel tituloLbl;
    // End of variables declaration//GEN-END:variables
}
